In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
data = pd.read_csv('PPMI_DL/dat_csv/SPECT_180430_4_30_2018.csv')
data

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded
0,770315,17608,Prodromal,M,62,5,SPECT,Reconstructed DaTSCAN,Processed,1/08/2016,DCM,NaN
1,323662,3000,Control,F,69,0,SPECT,Reconstructed DaTSCAN,Processed,1/20/2011,DCM,NaN
2,504827,3001,PD,M,69,11,SPECT,Reconstructed DaTSCAN,Processed,4/10/2015,DCM,NaN
3,449434,3001,PD,M,68,91,SPECT,Reconstructed DaTSCAN,Processed,4/25/2014,DCM,NaN
4,419651,3001,PD,M,67,7,SPECT,Reconstructed DaTSCAN,Processed,5/03/2013,DCM,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1712,504421,51440,GenCohort PD,M,70,0,SPECT,Reconstructed DaTSCAN,Processed,4/10/2015,DCM,NaN
1713,912277,51440,GenCohort PD,M,72,7,SPECT,Reconstructed DaTSCAN,Processed,5/11/2017,DCM,NaN
1714,679879,51867,GenCohort Unaff,F,65,0,SPECT,Reconstructed DaTSCAN,Processed,8/20/2015,DCM,NaN
1715,846391,53677,GenCohort Unaff,F,63,0,SPECT,Reconstructed DaTSCAN,Processed,6/30/2016,DCM,NaN
1716,846210,57605,GenCohort Unaff,F,65,0,SPECT,Reconstructed DaTSCAN,Processed,2/23/2017,DCM,NaN

In [4]:
# Extract the Image Data ID column
image_data_ids = data['Subject']

# Convert the IDs to a comma-separated string
ids_string = ','.join(map(str, image_data_ids))

# Write the string to a text file
with open('subject_data_ids.txt', 'w') as file:
    file.write(ids_string)